<?php

return [
    'us_states' => [
        'AL' => 'Alabama', 'AK' => 'Alaska', 'AZ' => 'Arizona', 'AR' => 'Arkansas', 'CA' => 'California',
        'CO' => 'Colorado', 'CT' => 'Connecticut', 'DE' => 'Delaware', 'DC' => 'District of Columbia', 'FL' => 'Florida',
        'GA' => 'Georgia', 'HI' => 'Hawaii', 'ID' => 'Idaho', 'IL' => 'Illinois', 'IN' => 'Indiana',
        'IA' => 'Iowa', 'KS' => 'Kansas', 'KY' => 'Kentucky', 'LA' => 'Louisiana', 'ME' => 'Maine',
        'MD' => 'Maryland', 'MA' => 'Massachusetts', 'MI' => 'Michigan', 'MN' => 'Minnesota', 'MS' => 'Mississippi',
        'MO' => 'Missouri', 'MT' => 'Montana', 'NE' => 'Nebraska', 'NV' => 'Nevada', 'NH' => 'New Hampshire',
        'NJ' => 'New Jersey', 'NM' => 'New Mexico', 'NY' => 'New York', 'NC' => 'North Carolina', 'ND' => 'North Dakota',
        'OH' => 'Ohio', 'OK' => 'Oklahoma', 'OR' => 'Oregon', 'PA' => 'Pennsylvania', 'RI' => 'Rhode Island',
        'SC' => 'South Carolina', 'SD' => 'South Dakota', 'TN' => 'Tennessee', 'TX' => 'Texas', 'UT' => 'Utah',
        'VT' => 'Vermont', 'VA' => 'Virginia', 'WA' => 'Washington', 'WV' => 'West Virginia', 'WI' => 'Wisconsin', 'WY' => 'Wyoming',
    ],
    'gb_counties' => [
        'Bedfordshire' => 'Bedfordshire',
        'Berkshire' => 'Berkshire',
        'Bristol' => 'Bristol',
        'Buckinghamshire' => 'Buckinghamshire',
        'Cambridgeshire' => 'Cambridgeshire',
        'Cheshire' => 'Cheshire',
        'City of London' => 'City of London',
        'Cornwall' => 'Cornwall',
        'Cumbria' => 'Cumbria',
        'Derbyshire' => 'Derbyshire',
        'Devon' => 'Devon',
        'Dorset' => 'Dorset',
        'Durham' => 'Durham',
        'East Riding of Yorkshire' => 'East Riding of Yorkshire',
        'East Sussex' => 'East Sussex',
        'Essex' => 'Essex',
        'Gloucestershire' => 'Gloucestershire',
        'Greater London' => 'Greater London',
        'Greater Manchester' => 'Greater Manchester',
        'Hampshire' => 'Hampshire',
        'Herefordshire' => 'Herefordshire',
        'Hertfordshire' => 'Hertfordshire',
        'Isle of Wight' => 'Isle of Wight',
        'Kent' => 'Kent',
        'Lancashire' => 'Lancashire',
        'Leicestershire' => 'Leicestershire',
        'Lincolnshire' => 'Lincolnshire',
        'Merseyside' => 'Merseyside',
        'Norfolk' => 'Norfolk',
        'North Yorkshire' => 'North Yorkshire',
        'Northamptonshire' => 'Northamptonshire',
        'Northumberland' => 'Northumberland',
        'Nottinghamshire' => 'Nottinghamshire',
        'Oxfordshire' => 'Oxfordshire',
        'Rutland' => 'Rutland',
        'Shropshire' => 'Shropshire',
        'Somerset' => 'Somerset',
        'South Yorkshire' => 'South Yorkshire',
        'Staffordshire' => 'Staffordshire',
        'Suffolk' => 'Suffolk',
        'Surrey' => 'Surrey',
        'Tyne and Wear' => 'Tyne and Wear',
        'Warwickshire' => 'Warwickshire',
        'West Midlands' => 'West Midlands',
        'West Sussex' => 'West Sussex',
        'West Yorkshire' => 'West Yorkshire',
        'Wiltshire' => 'Wiltshire',
        'Worcestershire' => 'Worcestershire',
        'Antrim' => 'Antrim',
        'Armagh' => 'Armagh',
        'Down' => 'Down',
        'Fermanagh' => 'Fermanagh',
        'Londonderry' => 'Londonderry',
        'Tyrone' => 'Tyrone',
        'Blaenau Gwent' => 'Blaenau Gwent',
        'Bridgend' => 'Bridgend',
        'Caerphilly' => 'Caerphilly',
        'Cardiff' => 'Cardiff',
        'Carmarthenshire' => 'Carmarthenshire',
        'Ceredigion' => 'Ceredigion',
        'Conwy' => 'Conwy',
        'Denbighshire' => 'Denbighshire',
        'Flintshire' => 'Flintshire',
        'Gwynedd' => 'Gwynedd',
        'Isle of Anglesey' => 'Isle of Anglesey',
        'Merthyr Tydfil' => 'Merthyr Tydfil',
        'Monmouthshire' => 'Monmouthshire',
        'Neath Port Talbot' => 'Neath Port Talbot',
        'Newport' => 'Newport',
        'Pembrokeshire' => 'Pembrokeshire',
        'Powys' => 'Powys',
        'Rhondda Cynon Taf' => 'Rhondda Cynon Taf',
        'Swansea' => 'Swansea',
        'Torfaen' => 'Torfaen',
        'Vale of Glamorgan' => 'Vale of Glamorgan',
        'Wrexham' => 'Wrexham',
        'Aberdeen City' => 'Aberdeen City',
        'Aberdeenshire' => 'Aberdeenshire',
        'Angus' => 'Angus',
        'Argyll and Bute' => 'Argyll and Bute',
        'City of Edinburgh' => 'City of Edinburgh',
        'Clackmannanshire' => 'Clackmannanshire',
        'Dumfries and Galloway' => 'Dumfries and Galloway',
        'Dundee City' => 'Dundee City',
        'East Ayrshire' => 'East Ayrshire',
        'East Dunbartonshire' => 'East Dunbartonshire',
        'East Lothian' => 'East Lothian',
        'East Renfrewshire' => 'East Renfrewshire',
        'Falkirk' => 'Falkirk',
        'Fife' => 'Fife',
        'Glasgow City' => 'Glasgow City',
        'Highland' => 'Highland',
        'Inverclyde' => 'Inverclyde',
        'Midlothian' => 'Midlothian',
        'Moray' => 'Moray',
        'Na h-Eileanan Siar (Western Isles)' => 'Na h-Eileanan Siar (Western Isles)',
        'North Ayrshire' => 'North Ayrshire',
        'North Lanarkshire' => 'North Lanarkshire',
        'Orkney Islands' => 'Orkney Islands',
        'Perth and Kinross' => 'Perth and Kinross',
        'Renfrewshire' => 'Renfrewshire',
        'Scottish Borders' => 'Scottish Borders',
        'Shetland Islands' => 'Shetland Islands',
        'South Ayrshire' => 'South Ayrshire',
        'South Lanarkshire' => 'South Lanarkshire',
        'Stirling' => 'Stirling',
        'West Dunbartonshire' => 'West Dunbartonshire',
        'West Lothian' => 'West Lothian',
    ],
    'au_states' => [
        'NSW' => 'New South Wales',
        'VIC' => 'Victoria',
        'QLD' => 'Queensland',
        'SA'  => 'South Australia',
        'WA'  => 'Western Australia',
        'TAS' => 'Tasmania',
        'NT'  => 'Northern Territory',
        'ACT' => 'Australian Capital Territory',
    ],
    'de_states' => [
        'BW' => 'Baden-Württemberg',
        'BY' => 'Bayern',
        'BE' => 'Berlin',
        'BB' => 'Brandenburg',
        'HB' => 'Bremen',
        'HH' => 'Hamburg',
        'HE' => 'Hessen',
        'MV' => 'Mecklenburg-Vorpommern',
        'NI' => 'Niedersachsen',
        'NW' => 'Nordrhein-Westfalen',
        'RP' => 'Rheinland-Pfalz',
        'SL' => 'Saarland',
        'SN' => 'Sachsen',
        'ST' => 'Sachsen-Anhalt',
        'SH' => 'Schleswig-Holstein',
        'TH' => 'Thüringen',
    ],
    'fr_regions' => [
        'IDF' => 'Île-de-France',
        'ARA' => 'Auvergne-Rhône-Alpes',
        'NAQ' => 'Nouvelle-Aquitaine',
        'OCC' => 'Occitanie',
        'PACA' => 'Provence-Alpes-Côte d’Azur',
        'HDF' => 'Hauts-de-France',
        'NOR' => 'Normandie',
        'BRE' => 'Bretagne',
        'CVL' => 'Centre-Val de Loire',
        'BFC' => 'Bourgogne-Franche-Comté',
        'PDL' => 'Pays de la Loire',
        'GES' => 'Grand Est',
        'COR' => 'Corse',
    ],
];


